/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.matheus.fatguys.htm.jankenpo.gui;

import br.com.matheus.fatguys.htm.jankenpo.JanKenPoEnum;
import java.awt.Color;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author y2gh
 */
public class JanKenPoDialog extends javax.swing.JDialog {

    private JanKenPoModel model = new JanKenPoModel();

    public JanKenPoModel getModel() {
        return model;
    }

    /**
     * Creates new form JoKenPoDialog
     */
    public JanKenPoDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        String player = JOptionPane.showInputDialog("Player Name: ");
        if (player == null || "".equals(player)) {
            player = "PLAYER1";
        }
        model.setPlayerName(player);
        panelRandom.setVisible(false);
        model.setVersusHtm(true);
        try {
            model.init();
        } catch (IOException ex) {
            Logger.getLogger(JanKenPoModel.class.getName()).log(Level.SEVERE, null, ex);
        }
        htmLabels();
        panelLog.setVisible(chkShowLog.isSelected());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        panelYou = new javax.swing.JPanel();
        btnReset = new javax.swing.JButton();
        lblYourPointsVsHtm = new javax.swing.JLabel();
        lblJanYour = new javax.swing.JLabel();
        lblKenYour = new javax.swing.JLabel();
        lblPoYour = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblYouWin = new javax.swing.JLabel();
        panelRandom = new javax.swing.JPanel();
        lblRandomPoints = new javax.swing.JLabel();
        panelHtm = new javax.swing.JPanel();
        lblHTMPoints = new javax.swing.JLabel();
        lblHtmPo = new javax.swing.JLabel();
        lblHtmJan = new javax.swing.JLabel();
        lblHtmKen = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblHtmWin = new javax.swing.JLabel();
        surprisedBar = new javax.swing.JProgressBar();
        jLabel5 = new javax.swing.JLabel();
        chkShowLog = new javax.swing.JCheckBox();
        btnSaveNetwork = new javax.swing.JButton();
        panelLog = new javax.swing.JPanel();
        paneLog = new javax.swing.JScrollPane();
        lstLog = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        panelYou.setBorder(javax.swing.BorderFactory.createTitledBorder("You"));

        btnReset.setText("Reset");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        lblYourPointsVsHtm.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${model.yourPointsVsHtm}"), lblYourPointsVsHtm, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        lblJanYour.setIcon(new javax.swing.ImageIcon(getClass().getResource("/JAN.png"))); // NOI18N
        lblJanYour.setText("JAN");
        lblJanYour.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblJanYourMouseClicked(evt);
            }
        });

        lblKenYour.setIcon(new javax.swing.ImageIcon(getClass().getResource("/KEN.png"))); // NOI18N
        lblKenYour.setText("KEN");
        lblKenYour.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblKenYourMouseClicked(evt);
            }
        });

        lblPoYour.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PO.png"))); // NOI18N
        lblPoYour.setText("PO");
        lblPoYour.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblPoYourMouseClicked(evt);
            }
        });

        jLabel1.setText("Points:");

        jLabel3.setText("Name:");

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${model.playerName}"), jLabel4, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        lblYouWin.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblYouWin.setText("jLabel5");

        javax.swing.GroupLayout panelYouLayout = new javax.swing.GroupLayout(panelYou);
        panelYou.setLayout(panelYouLayout);
        panelYouLayout.setHorizontalGroup(
            panelYouLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelYouLayout.createSequentialGroup()
                .addComponent(btnReset)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(panelYouLayout.createSequentialGroup()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(panelYouLayout.createSequentialGroup()
                .addGroup(panelYouLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblJanYour, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblKenYour, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblPoYour, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelYouLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblYourPointsVsHtm, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addComponent(lblYouWin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panelYouLayout.setVerticalGroup(
            panelYouLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelYouLayout.createSequentialGroup()
                .addComponent(lblYouWin, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelYouLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblYourPointsVsHtm, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblJanYour)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblKenYour)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblPoYour)
                .addGap(18, 18, 18)
                .addGroup(panelYouLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(btnReset))
        );

        panelRandom.setBorder(javax.swing.BorderFactory.createTitledBorder("Random"));

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${model.randomPoints}"), lblRandomPoints, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        javax.swing.GroupLayout panelRandomLayout = new javax.swing.GroupLayout(panelRandom);
        panelRandom.setLayout(panelRandomLayout);
        panelRandomLayout.setHorizontalGroup(
            panelRandomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblRandomPoints, javax.swing.GroupLayout.DEFAULT_SIZE, 71, Short.MAX_VALUE)
        );
        panelRandomLayout.setVerticalGroup(
            panelRandomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRandomLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(lblRandomPoints, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelHtm.setBorder(javax.swing.BorderFactory.createTitledBorder("HTM"));

        lblHTMPoints.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${model.htmPoints}"), lblHTMPoints, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        lblHtmPo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PO.png"))); // NOI18N
        lblHtmPo.setText("PO");

        lblHtmJan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/JAN.png"))); // NOI18N
        lblHtmJan.setText("JAN");

        lblHtmKen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/KEN.png"))); // NOI18N
        lblHtmKen.setText("KEN");

        jLabel2.setText("Points:");

        lblHtmWin.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblHtmWin.setText("jLabel6");

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${model.anomaly}"), surprisedBar, org.jdesktop.beansbinding.BeanProperty.create("value"));
        bindingGroup.addBinding(binding);

        jLabel5.setText("How Surprised HTM is:");

        chkShowLog.setText("Show Log");
        chkShowLog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkShowLogActionPerformed(evt);
            }
        });

        btnSaveNetwork.setText("Save Network");
        btnSaveNetwork.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveNetworkActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelHtmLayout = new javax.swing.GroupLayout(panelHtm);
        panelHtm.setLayout(panelHtmLayout);
        panelHtmLayout.setHorizontalGroup(
            panelHtmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblHtmWin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(surprisedBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panelHtmLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelHtmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblHtmPo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblHtmKen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelHtmLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblHTMPoints, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(panelHtmLayout.createSequentialGroup()
                        .addComponent(lblHtmJan, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                        .addContainerGap())))
            .addGroup(panelHtmLayout.createSequentialGroup()
                .addGroup(panelHtmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelHtmLayout.createSequentialGroup()
                        .addComponent(chkShowLog)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSaveNetwork))
                    .addComponent(jLabel5))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        panelHtmLayout.setVerticalGroup(
            panelHtmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelHtmLayout.createSequentialGroup()
                .addComponent(lblHtmWin, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelHtmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblHTMPoints, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblHtmJan, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblHtmKen)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblHtmPo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelHtmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkShowLog)
                    .addComponent(btnSaveNetwork))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(surprisedBar, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        panelLog.setBorder(javax.swing.BorderFactory.createTitledBorder("Log"));

        org.jdesktop.beansbinding.ELProperty eLProperty = org.jdesktop.beansbinding.ELProperty.create("${model.htmLogList}");
        org.jdesktop.swingbinding.JListBinding jListBinding = org.jdesktop.swingbinding.SwingBindings.createJListBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, eLProperty, lstLog);
        bindingGroup.addBinding(jListBinding);

        paneLog.setViewportView(lstLog);

        javax.swing.GroupLayout panelLogLayout = new javax.swing.GroupLayout(panelLog);
        panelLog.setLayout(panelLogLayout);
        panelLogLayout.setHorizontalGroup(
            panelLogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(paneLog, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE)
        );
        panelLogLayout.setVerticalGroup(
            panelLogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(paneLog, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelYou, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelRandom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelHtm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelLog, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelLog, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelYou, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelHtm, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelRandom, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        try {
            model.reset();
        } catch (IOException ex) {
            Logger.getLogger(JanKenPoDialog.class.getName()).log(Level.SEVERE, null, ex);
        }
        htmLabels();
    }//GEN-LAST:event_btnResetActionPerformed

    private void lblJanYourMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblJanYourMouseClicked
        model.setYourGuess(JanKenPoEnum.JAN);
        model.play();
        htmLabels();
    }//GEN-LAST:event_lblJanYourMouseClicked

    private void lblKenYourMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblKenYourMouseClicked
        model.setYourGuess(JanKenPoEnum.KEN);
        model.play();
        htmLabels();
    }//GEN-LAST:event_lblKenYourMouseClicked

    private void lblPoYourMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblPoYourMouseClicked
        model.setYourGuess(JanKenPoEnum.PO);
        model.play();
        htmLabels();
    }//GEN-LAST:event_lblPoYourMouseClicked

    private void btnSaveNetworkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveNetworkActionPerformed
        model.saveNetwork();
    }//GEN-LAST:event_btnSaveNetworkActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        model.saveNetwork();
    }//GEN-LAST:event_formWindowClosing

    private void chkShowLogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkShowLogActionPerformed
        panelLog.setVisible(chkShowLog.isSelected());
        this.repaint();
    }//GEN-LAST:event_chkShowLogActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JanKenPoDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JanKenPoDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JanKenPoDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JanKenPoDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JanKenPoDialog dialog = new JanKenPoDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnSaveNetwork;
    private javax.swing.JCheckBox chkShowLog;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel lblHTMPoints;
    private javax.swing.JLabel lblHtmJan;
    private javax.swing.JLabel lblHtmKen;
    private javax.swing.JLabel lblHtmPo;
    private javax.swing.JLabel lblHtmWin;
    private javax.swing.JLabel lblJanYour;
    private javax.swing.JLabel lblKenYour;
    private javax.swing.JLabel lblPoYour;
    private javax.swing.JLabel lblRandomPoints;
    private javax.swing.JLabel lblYouWin;
    private javax.swing.JLabel lblYourPointsVsHtm;
    private javax.swing.JList<String> lstLog;
    private javax.swing.JScrollPane paneLog;
    private javax.swing.JPanel panelHtm;
    private javax.swing.JPanel panelLog;
    private javax.swing.JPanel panelRandom;
    private javax.swing.JPanel panelYou;
    private javax.swing.JProgressBar surprisedBar;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables

    private void htmLabels() {
        JanKenPoEnum jkp = model.getHtmPreviousGuess();
        lblHtmJan.setVisible(jkp != null && jkp.equals(JanKenPoEnum.JAN));
        lblHtmKen.setVisible(jkp != null && jkp.equals(JanKenPoEnum.KEN));
        lblHtmPo.setVisible(jkp != null && jkp.equals(JanKenPoEnum.PO));
        if (jkp == null || model.getYourGuess() == null) {
            lblHtmWin.setText("");
            lblHtmWin.setForeground(Color.WHITE);
            lblYouWin.setText("");
            lblYouWin.setForeground(Color.WHITE);
        } else if (jkp.wins(model.getYourGuess())) {
            lblHtmWin.setText("HTM WINS");
            lblHtmWin.setForeground(Color.GREEN);
            lblYouWin.setText("YOU LOSE");
            lblYouWin.setForeground(Color.RED);
        } else if (model.getYourGuess().wins(jkp)) {
            lblYouWin.setText("YOU WIN");
            lblYouWin.setForeground(Color.GREEN);
            lblHtmWin.setText("HTM LOSES");
            lblHtmWin.setForeground(Color.RED);
        } else {
            lblYouWin.setText("DRAW");
            lblYouWin.setForeground(Color.LIGHT_GRAY);
            lblHtmWin.setText("DRAW");
            lblHtmWin.setForeground(Color.LIGHT_GRAY);
        }
        if(model.getAnomaly()>0.8){
            surprisedBar.setBackground(Color.red);
        }
        else if(model.getAnomaly()>0.6){
            surprisedBar.setBackground(Color.orange);
        }
        else if(model.getAnomaly()>0.4){
            surprisedBar.setBackground(Color.yellow);
        }
        else if(model.getAnomaly()>0.2){
            surprisedBar.setBackground(Color.blue);
        }
        else {
            surprisedBar.setBackground(Color.green);
        }
    }
}
